const { chromium } = require(process.env.MOVINIGHT_PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
let browser;
(async () => {
  browser = await chromium.connectOverCDP('http://127.0.0.1:9229');
  const page = browser.contexts().flatMap(c=>c.pages()).find(p=>p.url().includes('tauri.localhost'));
  assert(page,'Real Tauri WebView is running');
  assert(fs.existsSync('.qa-data/config.json'),'Use the isolated QA data folder');
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const invoke=(command,args={})=>page.evaluate(({command,args})=>window.__TAURI__.core.invoke(command,args),{command,args});
  const report={checks:[]};
  const passed=name=>{report.checks.push(name);console.log('PASS',name);};
  await page.reload();await page.waitForSelector('#results-grid .result-card');
  const layout=await page.locator('.compact-discover').boundingBox();const first=await page.locator('#results-grid .result-card').first().boundingBox();
  assert(layout.height<370);assert(first.y<600);passed('Desktop filters and first movie row visible together');
  await page.locator('#genres-dropdown summary').click();
  await page.locator('.genre-chip[data-id="28"]').click();await page.locator('.genre-chip[data-id="878"]').click();
  assert.match(await page.locator('#genres-summary').innerText(),/Action.*Science Fiction/);
  await page.locator('#search-btn').click();await page.waitForSelector('#results-grid .result-card');
  const result=await invoke('search_movies',{query:'',page:1,yearFrom:null,yearTo:null,genreIds:[28,878],sortBy:'popularity.desc',excludeAnimation:false,withWatchProviders:[],withOriginalLanguage:null,minRating:0});
  assert(result.results.every(i=>i.genre_ids.includes(28)||i.genre_ids.includes(878)));
  assert(result.results.some(i=>!(i.genre_ids.includes(28)&&i.genre_ids.includes(878))));passed('Live TMDB genre selection uses union, including single-genre titles');
  await page.locator('#results-grid .result-card').first().hover();
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('#results-grid .result-card'),'::before').opacity==='1');
  const rim=await page.locator('#results-grid .result-card').first().evaluate(el=>({opacity:getComputedStyle(el,'::before').opacity,mask:getComputedStyle(el,'::before').maskComposite}));
  assert.equal(rim.opacity,'1');assert(rim.mask.includes('exclude'));await page.screenshot({path:'.qa-output/rainbow-hover.png'});passed('Rainbow hover is a masked ring around the entire card');
  await page.locator('#reset-filters').click();await page.waitForSelector('#results-grid .result-card');
  await page.locator('#search-nav').click();await page.locator('#search-input').fill('Matrix');await page.locator('#search-name-btn').click();await page.waitForSelector('#search-name-results .result-card');
  const searchFirst=await page.locator('#search-name-results .result-card').count();
  await page.locator('#name-more').click();await page.waitForFunction(n=>document.querySelectorAll('#search-name-results .result-card').length>n,searchFirst);
  passed('Name search returns both media types and supports pagination');
  await page.locator('#search-input').fill('Interstellar');await page.locator('#search-name-btn').click();await page.locator('#search-clear-btn').click();
  await page.waitForTimeout(900);assert.equal(await page.locator('#search-name-results .result-card').count(),0);passed('Clearing search prevents delayed responses from restoring old results');
  await page.locator('#research-nav').click();
  const researchText='| Title | Year | Type |\n| The General | 1926 | Movie |\n| Arrival | 2016 | Movie |';
  await page.locator('#research-text').fill(researchText);await page.locator('#research-instructions').fill('Verify each title and year. Propose matches for my review.');await page.locator('#save-research').click();
  await page.waitForFunction(()=>document.querySelector('#research-save-state').textContent==='Saved locally');
  await page.screenshot({path:'.qa-output/reel-research.png'});
  const workspace=await invoke('get_ai_workspace');assert.equal(workspace.research.text,researchText);passed('Pasted research tables persist separately from library lists');
  const status=await invoke('start_mcp');assert(status.running);assert(status.token);
  let rpcId=0;
  const rpc=async(method,params={})=>{
    const response=await fetch(status.url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json, text/event-stream','Authorization':`Bearer ${status.token}`,'MCP-Protocol-Version':'2025-11-25'},body:JSON.stringify({jsonrpc:'2.0',id:++rpcId,method,params})});
    assert.equal(response.status,200);return response.json();
  };
  const call=async(name,args={})=>{const r=await rpc('tools/call',{name,arguments:args});assert.equal(r.result.isError,false,JSON.stringify(r));return JSON.parse(r.result.content[0].text);};
  const init=await rpc('initialize',{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'MoviNight QA',version:'1'}});assert.equal(init.result.serverInfo.version,'1.1.0');
  const toolList=await rpc('tools/list');assert.equal(toolList.result.tools.length,8);assert(!toolList.result.tools.some(t=>/approve|remove/.test(t.name)));
  const noToken=await fetch(status.url,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(noToken.status,401);
  const evil=await fetch(status.url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${status.token}`,'Origin':'https://evil.example'},body:'{}'});assert.equal(evil.status,403);
  passed('Actual local MCP handshake, tool discovery, token authentication and Origin validation');
  const library=await call('get_library');
  const originalWatched=JSON.parse(fs.readFileSync('.qa-data/backups/before-1.1.0/watched.json','utf8'));
  assert.equal(library.watched.length,originalWatched.length);
  for(const old of originalWatched){const current=library.watched.find(i=>i.id===old.id&&i.content_type===old.content_type);assert(current);assert.equal(current.watched_date,old.watched_date);if(old.watched_seasons)assert.deepEqual(current.watched_seasons,old.watched_seasons);}
  passed('Installed legacy library copies retain every watched title, date and tracked season');
  const research=await call('get_research');assert.equal(research.id,workspace.research.id);
  const matches=await call('search_titles',{query:'The General',content_type:'movie'});
  const match=matches.movies.results.find(i=>!library.waitlist.some(l=>l.id===i.id&&l.content_type==='movie'));
  assert(match,'An unlisted candidate is available for isolated approval testing');
  const args={id:match.id,content_type:'movie',requested_title:'The General (1926)',reason:'Runtime QA: canonical title, release year and movie type verified against TMDB. Review the displayed year before approving.',research_id:research.id};
  const proposal=await call('propose_waitlist',args);assert.equal(proposal.status,'pending_user_approval');
  const duplicate=await call('propose_waitlist',args);assert.equal(duplicate.status,'already_pending');
  let after=await call('get_library');assert.equal(after.waitlist.length,library.waitlist.length);passed('MCP proposals stay outside waitlist; duplicate proposals are idempotent');
  await page.locator('#white-list-nav').click();await page.locator('#proposal-review').evaluate(el=>el.open=true);await page.waitForSelector('[data-proposal]');
  await page.screenshot({path:'.qa-output/proposal-review.png'});
  await page.locator(`[data-proposal="${proposal.proposal.proposal_id}"][data-review="approve"]`).click();
  await page.waitForFunction(()=>document.querySelector('#proposal-count').textContent==='0');
  after=await call('get_library');assert.equal(after.waitlist.length,library.waitlist.length+1);assert(after.waitlist.some(i=>i.id===match.id));passed('Only in-app approval adds canonical matches to the waitlist');
  const oldest=library.watched[0];
  await call('publish_suggestion',{id:oldest.id,content_type:oldest.content_type,source:'watched',reason:`An older favorite from your library, last marked watched on ${oldest.watched_date}.`});
  await page.locator('#picks-nav').click();await page.waitForSelector('.suggestion');await page.screenshot({path:'.qa-output/ai-picks.png'});
  assert.match(await page.locator('.suggestion-label').first().innerText(),/REWATCH/);passed('Agent suggestions appear in AI Picks with the original watched date');
  await page.locator('#settings-btn').click();await page.locator('[data-settings="mcp"]').click();await page.waitForFunction(()=>document.querySelector('#mcp-status').textContent.includes('Running'));await page.screenshot({path:'.qa-output/mcp-settings.png'});
  await page.locator('#close-settings').click();
  await page.reload();await page.waitForSelector('#main-app.show');await page.locator('#research-nav').click();assert.equal(await page.locator('#research-text').inputValue(),researchText);await page.locator('#picks-nav').click();await page.waitForSelector('.suggestion');passed('Research and picks survive an app WebView reload');
  await invoke('stop_mcp');assert.equal((await invoke('mcp_status')).running,false);passed('MCP can be stopped; server state is opt-in');
  assert.deepEqual(errors,[]);passed('No JavaScript runtime errors during the end-to-end flow');
  fs.writeFileSync('.qa-output/runtime-report.json',JSON.stringify(report,null,2));
  await page.locator('#discover-nav').click();await browser.close();
})().catch(async e=>{await browser?.close();console.error(e.stack);process.exitCode=1;});
